# \bibliography{~/research/todo/bibtest}
* TODO 
[[todo]]
* Introduction
Giant cell tumor of bone affects a young adult population in the age
group of 20 to 40.cite:turcotte2002 15,57.  It also occurs
juxta-articular commonly around the knee.  Although it can rarely
metastasize, local cure and long survival is the rule.  Given its
propensity to be locally aggressive and recurrent, adequacy of initial
treatment can have lasting impact on risk of local recurrence and
function.  Intralesional surgery has acceptably low recurrence rates and
is function preserving making it the default choice when
feasible.  
Usual indications for resection have been extensive bone destruction,
large soft tissue mass,poor bone stock that does not allow internal
fixation despite cement augmentation,inability to preserve joint or
when sacrificing the bone provides best tumor control and minimal
functional impairment(eg fibular head or distal ulna).  

Local recurrence is treated in the same manner as if the
tumor were seen primarily.  Factors known to have impact on risk of
local recurrence are.....  Factors well known to not have a
significant impact on local recurrence are....

Usual clinical scenarios raising a dilemma of whether to resect or
curette are
1. Large juxta-articular tumor with soft tissue mass and poor
   subchondral bone
2. Multiply recurrent tumor
3. Pathological fracture
4. Pulmonary Metastasis associated with a primary or locally recurrent
   Giant Cell Tumor of bone
5. Referral after improper curettage in the community
6. Referral for a recurrent tumor from the community

Let us consider each of these scenarios .

1. Large juxa-articular tumors with little to no sub-chondral bone
   with flappy cartilage pose a challenge. Giant cell tumor is well
   resisted by cartilage and intra-articular tumor extension is
   unusual.  Articular cartilage with no subchondral bone can be
   challenging as one requires to balance preservation of cartilage
   with aggression of disease clearance.  Reconstruction is often
   supplemented with structural bone graft or cement augmentation to
   prevent articular collapse.  Some articular stiffness or early
   onset degenerative arthritis is to be expected.  Despite these
   challanges local control rates are not significantly worse in most
   series.  Local recurrences are managed like a primary and eventual
   cure is possible.  Wide resection can be associated with higher
   rate of complications 31 from cite:klenke2011 and have significant
   functional impairment 19,26,37.  Reconstruction usually
   necessitates megaprosthesis(22,31,46) or massive allografts (46)
   after sacrificing a significant segment of bone. 30,43,61.  The use
   of neoadjuvant denosumab for 5 to 6 months or even shorter to allow
   reconstitution of subchondral and peri-lesional bone that can
   maintain articular congruity, prevent collapse, prevent an
   impending fracture and allow a surface to curette against held
   promise. This has been successfully used to salvage joints that
   would otherwise have been resected.  This has however not reduced
   recurrence rates from baseline.  This likely is because Denosumab
   does not have a biologic activity against the neoplastic stromal
   cells and presence of ridges post denosumab makes disease clearance
   more challenging than at baseline.

In most recent publications over the last decade, referral for a
recurrent tumor was a significant risk factor for recurrence Tomeno,
Ochoa, Turcotte. LR rate for primary curettage was as low as 10 %.


Positve tumor margin or intra-operative contamination is a known risk
factor for local recurrence 25,30 in turcotte


* Outcomes of Resection vs Currettage

* Has Denosumab changed the landscape
* Conclusions
In conclusion curettage with or without adjuvants and reconstruction
allows good local control and excellent function.  Presence of a
pathological fracture , or sub-optimal curettage in the community
before referral or multiple recurrences are not indications for
resection in of itself.Unless extent of soft tissue involvement or
sheer size precludes it, recurrences can usually be salvaged with
curettage with reasonable succes rates.  In locations that allow
acceptable function with resection without reconstruction (rib,
fibular head,distal ulna) ; or locations where repeated recurrence has made disease
control or meaningful reconstruction difficult to impossible with
curettage alone ; and vertebral GCT... * TODO  Resection is associated with lower
recurrence rate but higher risk of complication and slightly inferior
function.  Denosumab has allowed restoration of bone stock and salvage
in large juxta-articular lesions with poor subchondral bone which
would likely have been resected in the past.Based on current evidence
it does not seem to reduce recurrence rates.  Pulmonary metastasis is
rare and associated with excellent long term outcome and should not by itself create an indication for wide resection.
* Scratch

cite:sung1982 Recurrence 41.2 % with currettage and 7 % with resection 

cite:prosser2005
Giant cell tumors of bone are locally agressive benign bone tumors
with a rare tendency to metastasize. Local recurrence can be
unpredictable and makes initial choice of treatment
challenging. Reported local recurrence rates with currettage have
ranged from 0-47 %; with resection have ranged from 0-10%
7 % LR in grade 1,2 29% in grade 3. No other sginificant factor for
local recurrence. 91 % overall treated successfully with curettage
alone. Without giving details about 10 % had primary excision with
eprs or with WLE with only one recurrence in this group.For
recurrences most resections were done for 3rd recurrence.Functional
scores were similar but marginally lower in the resection
group.Regardless of adjuvant used its the efficacy of the initial
currettage that likely impacts outcome (4,24,28)
Although mention was made that resection was done in patients with
extensive disease, no comment was made on objective criteria to
suggest what aggressive disease means.Recurrence rates do not seem to
correlate with age, gender , tumor size or distance to articular
surface (21,2,25) Important factors are width of the surgical window
(8 )and adequacy of margin 20,21,25. Capanna had a recurrence rate of
48% with less than 50% and 26 % with more than 50 %
Recurrence rates are higher with curretage than excision
20,21,25.  Gitelis 16 reported wide loacl excisions with or without an
EPR had higher complications and poorer function. MEan functional
score of 23/30 with enbloc excisions and 29/30 with curettage and
complication of 33 vs 10 %. Prosse et al had 3% vs 11%.
No evidence to link histologic grade as given by JAffe and its
aggressiveness.  Campanacci data showed no correlation between radiologic
grade and recurrence.2- 21% present with path fracture 3,6,23,27. This
series had 22.4 %. Presence of fracture does not lead to increased
recurrence rate.  Drenhoffer 11 path frac can be treated adequately.
Prosser data shows 100 % success in primary curettage despite a
recuurence.80% in referred from elsewhere.

cite:turcotte2002
Rate of local control historically has been between 25 to 50 %. Wide
resection associated with better local control but worse
morbidity.Most GCTs are benign (50) and located peri-articular.
Recurrence rates were similar in resection and curettage group.
Presence of pathologocal fracture or Campanacci grade 3 were not
significant risk factors for local recurrence.  Importantly cement was
more often used in lower grade lesions and bone graft in higher grade
lesions and in pathological fractures.

cite:klenke2011
Wide resection had a lower recurrence rate than curettage 5 vs 25
%.Although curettage was in equal proportionsin T1 and T2 tumors,
proportion of excsions in patients with a path fracture was 47% vs 14%
in those without. This may underestimate the risk of recurrence in
path fracture group.
 
