# \bibliography{~/research/todo/bibtest}
* Least Hazard ratios detected with 80% power
* landmark survival curve
cumulative probability is a conditional probability where pr3 is
probability of surviving year 3 + cumulative probability of surving
year 1 and 2
* Kaplan Meier and Cox proportional hazard model
Kaplam meier is Actuarial survival with 4 exceptions.
1. exact time of death is used instead of an arbitary interval.
2. survival function is calculated only when an outcome occurs.
3. curve derived changes every time an outcome occurs even if its
   within a range
4. steps on an actuarial graph are equal, not so on a KM curve

assumptions of a survival analysis
1. identifiable starting point
2. dichotomous wel defined end point
3. LTFU should not be related to outcome
4. to look for secular trend for long recruitment periods
* Mantel Cox Log Rank test Cox proportional Hazards Model
powerful non parametric test used on parametric survival data to
compare between 2 groups.It works like the CHi squared test and
assumes that if null is true (observed - expected) then the outcomes
should be distributed in proportion to the number of people at risk in
both groups.

If Chi square is significant we can look at RR which is significant if
over 2

in the presence of covariates : we need a test that
1. handle any number of covariates
2. treat continuous data as continuous
3. give a size effect

This is the Cox Proportional Hazard model qt = Dt/Rt , the prop hazard
at time t is the probability of the event at t , given survival upto t
and for a specific value of prognostic variable x , x1, x2 etc and x
can be discrete or continuous.

The assumption is that the effect of x does not change with time, or
RR for a specif value of X doesn not change over time.
h (t|x) = c(t) X f(x)
y = exp(-kt)

so RR = exp (-kt1)/ exp (-kt2) if its 0.67 it says that t is
protective. longer t1 has decreased the risk by 33 % , so only 2/3 the
risk at t1

as an example of sample size calculation if for
alpha 0.05 and beta 0.20 and delta of 2, we need 33 events per group
and if 25 % of participants are likely to have outcomes then 33/ 25
=132 participants per group

delta is a ratio of hazard h at a given time of 5 or 10 years.
* Survival analysis and Critique of conventional methods
Fractional polynomial approach to continuous variable
analysis in cox proportional hazard model.cite:sauerbrei1999

* Cumulative Incidence Competing Risk , Fine and Gray model, Subdistribution Hazard Ratio

** Hazard Ratio
 An intuitive explanation of the hazard can be given in the situation
 when time is discrete. In this instance, the hazard at a certain time
 is the probability to die at that time point in those patients who
 are still alive (2). In absence of competing risk, there is a 1:1
 mathematical relation between the hazard function and the survival
 function.

** Cox proportional Hazard
For example, smoking increases the hazard to develop dementia, but
only few smokers will actually develop dementia because of the
competing effects of death because of cancer or cardiovascular
diseases. As a result, it could happen that actually fewer smokers
than nonsmokers will experience dementia (ie, the cumulative incidence
of dementia is lower in the smoking group), even though the
cause-specific hazard ratio for the effect of smoking on dementia may
actually be larger than 1. Assuming that there is a biological
relation between smoking and dementia, this relation can be found by
the Cox regression model (ie, the HR is higher than 1 for smokers)
while the cumulative incidence of dementia is in fact lower in smokers
because of competing causes of death.

** fine and Gray model
The Fine and Gray model (9) links the effect of risk factors directly to the cause-specific cumulative incidences of death. In our smoking/dementia example, the Fine and Gray model considers the direct effect of smoking on the cumulative incidence of dementia (which was lower for smokers because of the competing risks). The effects of risk factors are expressed in subdistribution hazard ratios (SHR), where the subdistribution hazard function has a 1:1 relation with the cause-specific cumulative distribution function. An intuitive interpretation of this SHR is difficult, but readers should be reminded that an SHR above 1 corresponds to higher cause-specific event probabilities. In our dementia example, the Fine and Gray model will yield an SHR below 1 as it directly models the cumulative incidence of developing dementia in both subgroups, resulting in a lower risk of dementia for smokers. For a more detailed theoretical background of these models, we refer to Putter et al. (3).

http://www.nature.com/bmt/journal/v40/n4/full/1705727a.html
http://www.stat.unipg.it/luca/R
at any point in time, the overall 1-KM is equal to the sum of the CIFs
for each type of event.3, 4 Moreover, to assess the statistical
significance of a prognostic factor in a cumulative incidence analysis
Gray's test5 is one of the appropriate tests to perform.

 http://jnci.oxfordjournals.org/content/108/5/djv366.full

We show that in populations with high frequency of competing events, it is important to consider which method is most appropriate to estimate cause-specific endpoints. We demonstrate that when calculating absolute cause-specific risks the Kaplan-Meier method overestimates risk of the event of interest and that the cumulative incidence competing risks (CICR) method, which takes competing risks into account, should be used instead.

** Etiologic vs predictive research
we want to highlight the difference between etiological and predictive research questions in the comparison between the Cox proportional hazards model and the Fine and Gray model. In Example 1, the Fine and Gray model yielded rather strange results from an etiologic point of view as it suggests that psychiatric disorders are protective for recurrence. It is very unlikely that there is some biological mechanism in which psychiatric disorders are protective for breast cancer recurrence. More likely, our finding can be explained by the fact that the Fine and Gray analysis incorporates the competing risk of death, which influences the cumulative incidences of recurrence. This makes sense because patients with psychiatric disorders (especially dementia) have an increased risk of dying compared with patients without psychiatric disorders and patients who have died cannot get a breast cancer recurrence anymore. In contrast, the Cox regression model considers the effect on the cause-specific hazards, ie, on the instantaneous risk of recurrence for patients who are still at risk for the event at a certain time point, which is what interested us in this research question.
Therefore, in etiologic research questions, the Cox regression model is often the most appropriate method. In contrast, for predictive studies, methods that incorporate competing events such as Fine and Gray competing risk regression are more appealing because they provide a single summary value for the association between a risk variable and the cumulative cause-specific risk. In this case, it is important to consider that patients with a large risk of experiencing a competing event are unlikely to develop a breast cancer recurrence. Note that in this Commentary we focused on the choice of the appropriate measures for the effect of risk factors on breast cancer recurrence. Estimates of absolute mortality probabilities for specific causes as functions of risk variables can be obtained from either of the two models. For the Cox model approach, this implies estimating the cause-specific hazard ratios and using the Aalen-Johansen estimator to get the cumulative incidences, a direct extension of the CICR method, which can be carried out in, for example, the R packages mstate and survival (3,17,18). A major advantage of this Cox model approach is that it ensures that the sum of the cause-specific cumulative incidence equals the total cumulative incidence of experiencing any of the endpoints. This is not guaranteed when calculating cumulative incidences using Fine and Gray models. Another statistical argument in favor of modeling the cause-specific hazards using Cox models is that the proportional hazard assumption is often not unreasonable and can straightforwardly be checked. The proportional sub distribution hazard assumption in the Fine and Gray model is unlikely to hold over longer time periods. Moreover, the proportional subdistribution hazard assumptions of the Fine and Gray model will generally not hold for each of the different endpoints, and using Fine and Gray models to calculate absolute mortality probabilities could therefore yield impossible results (19,20). Hence, the Fine and Gray model does have some major limitations that should be taken into account.

These issues that we highlight are especially important for studies in older patients with indolent cancer types such as prostate cancer or hormone receptor-positive breast cancer as the risk of competing mortality is generally large in these studies, especially in studies that require a long period of follow-up (eg, adjuvant studies). In addition, the issue of competing mortality should be considered in other populations with a large frequency of competing events as well, such as populations with many concomitant diseases or a limited performance status, even if these are not limited to older patients. In contrast, the issue of competing mortality does not play a major role in studies that investigate older populations with highly aggressive tumors such as pancreas cancer or lung cancer as the risk of dying from the cancer itself is high in these populations, such that cancer-specific mortality will be almost similar to overall survival. This also applies to studies in the metastatic setting as patients with metastatic disease have a large risk of dying from cancer and follow-up is generally short.

In conclusion, in studies with cause-specific endpoints in populations with a high frequency of competing events, researchers should carefully choose the most appropriate statistical method in order to prevent incorrect interpretation of study results.

* Hazard Ratios
the hazard is usually denoted by h(t) and is the probability that an
individual who is under observation at a time t has an event at that
time. It represents the instantaneous event rate for an individual who
has already survived to time t.
The hazard ratio can be calculated to compare groups and, strictly speaking, is the effect on the hazard of
differences or 'covariates' (for example, drug treatment or control), as estimated by
regression models which treat the logarithm of the hazard rate as a function of a baseline
hazard, h0 (t). One method, the Cox model, is the most commonly used multivariate approach for analysing survival time data in medical research. It is based on an assumption that the hazards remain
proportionately constant and it is more correctly called the Cox
proportional hazards model.
a precise description of a hazard rate is the
'conditional instantaneous event rate
calculated as a function of time'.

In other words if hazard ratio is 0.77 and median OS is 13.5 mo, at
time t 77% of patients in the test group have the event compared to
100% in the control group, or 23 % people have benefited or do not have the
concernec event. 13.5 mo is median survival , which is when 50 % people had died of disease (if
OS is the end point)

* Relative risk
is a measure of how many events have occurred in a study expressed as a ratio
of the proportion of events occurring in the treatment group compared
with that in the control group. It is usually calculated at the end of the study and is quoted as having
occurred over the average or median duration of the trial. One pitfall
in therapeutic trials is picking a point in time to express the relative risk ratio of an event.
This can be misleading as it could be used to select the point in time at which there was
greatest separation between the treatment and the comparator arms. It
should only be calculated at the end of the clinical trial, and the
point at which the trial ends or is halted should be prespecified
(rather than chosen selectively after looking at the results!). Using
survival data and hazard ratios goes some way to preventing this type of

* Linear regression
http://math.usask.ca/~miket/S344D..pdf
many non linear curves can be put into linear form by appropriate
transformations. Using dummy variables categorical IVs can be
incorporated into lenear models. Variable transformation technique can
convert non linear behaviour into linear behaviour
http://dss.princeton.edu/training/Regression101.pdf
http://www.princeton.edu/~otorres/Regression101R.pdf

* ACE reports
Time to event variables like OS and EFS are reported with HR.
Dichotomous variables are reported with RR.

** Questions to ask when reading a Trial
1. Was the allocation sequence adequately generated?
2. Was it concealed?
3. Was the provider blinded?
4. Was the patient blinded?
5. Was the assessor blnded?
6. Was the follow up adequate?
7. Was the study free from selective outcome reporting?
8. Were the outcomes objective, patient important and assessed in a
   manner to limit bias?
9. Was the sample size large to assure a balance of prognosis and
   number of outcome events?
10. Was the investigator experience with treatments likely same ?
* Model building and selection:
Never let the computer do the thinking for you. Plot data, think about
a model, fit the model,plot the model, explain the model.
